PYSCRIPTS:=./main.py ./reader.py

all : run plot
	echo "All done"

plot : 
	echo "nothing to plot yet"

run : $(PYSCRIPTS)
	python main.py "./_data/Well1_561_only/HSE_647_donor_Bleedthrough_surface_density_20mW_200ms-200emgain_1_1/"
