#
# https://groups.google.com/g/datameet/c/fh-SRoAdLUE
#

all :
	python3 ./json2df.py https://gist.githubusercontent.com/punchagan/4d4c326f8c70850e1ac2914d7610f0c3/raw/e1ab24033d61d1643fb33b4a653fa657eeea9895/kolkata-parks.json > kolkata_parks.csv
